name: Markdown Check

on: [push, pull_request]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Markdown Linter
        uses: DavidAnson/markdownlint-cli2-action@v11
